SFACE_COSINE_THRESHOLD = 0.363
MATCH_THRESHOLD_STRICT = 0.45
MATCH_THRESHOLD_LENIENT = 0.363
MIN_FACE_PX = 32
MIN_FACE_ENROLL_PX = 80
FACE_DETECT_SCORE = 0.55
FACE_DETECT_SCORE_REG = 0.65
NEG_CACHE_TTL_S = 0.4
POS_CACHE_TTL_S = 2.5
FACE_EVAL_INTERVAL_FRAMES = 5
MAX_CACHE_ENTRIES = 512

AMBIGUITY_MARGIN = 0.05
TOP_K_CANDIDATES = 3

CONSENSUS_WINDOW_SIZE = 5
CONSENSUS_CONFIRM_MIN = 3
CONSENSUS_CONFIRM_WINDOW = 5
CONSENSUS_CANDIDATE_MIN = 2

QUALITY_LAPLACIAN_MIN = 60
QUALITY_LUMA_MIN = 50
QUALITY_LUMA_MAX = 205
QUALITY_POSE_RATIO_MIN = 0.65
QUALITY_POSE_RATIO_MAX = 1.55

LOW_LIGHT_LUMA_THRESHOLD = 60
LOW_LIGHT_CLAHE_CLIP = 2.0
LOW_LIGHT_CLAHE_GRID = (8, 8)

CALIBRATION_THRESHOLD_COSINE = 0.45
CALIBRATION_THRESHOLD_DISPLAY = 50.0
CALIBRATION_GENUINE_COSINE = 0.75
CALIBRATION_GENUINE_DISPLAY = 95.0
